# YAML Ain't Markup Language = ele guarda dados
# É montado em cima do JSON, mas inspirado em Python (indentação)

services:
  database:
    container_name: "postgres-dev"
    image: 'postgres:16.4-alpine3.20'
    env_file:
      - ../.env.development
    ports:
      - 2345:5432


